In [ ]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
print(list1.pop(0),list1+list2,len(list1))
list2.insert(1,2)
print(list2)

1 [2, 3, 4, 5, 6, 7, 8] 3
[5, 2, 6, 7, 8]


In [ ]:
tup = 1,2
print(tup)

(1, 2)


In [ ]:
#numpy code
import numpy as np
a = np.array([1,4,3,7,1,7,8,5])
print(a)
print(a.reshape(2,4))
np.array([[1,2],[3,4]])

[1 4 3 7 1 7 8 5]
[[1 4 3 7]
 [1 7 8 5]]


array([[1, 2],
       [3, 4]])

In [ ]:
print(np.arange(4,11))

[ 4  5  6  7  8  9 10]


In [ ]:
#data type
a = np.array([1,2,3,4], dtype=float)
a
a.dtype

dtype('float64')

In [ ]:
# numpy.ones(shape, dtype=None, order='C')
np.ones((1,3),dtype=int)

array([[1, 1, 1]])

In [ ]:
#numpy array zeros shape implementation:
np.zeros((4,3,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [ ]:
k = np.full((2,2),7)
k

array([[7, 7],
       [7, 7]])

In [ ]:
d = np.eye(2,2,dtype=int)
print(d)

[[1 0]
 [0 1]]


In [ ]:
e = np.random.random((2,2))
e

array([[0.05779541, 0.30916722],
       [0.16800623, 0.33587966]])

In [ ]:
#give a equal split value for given range......
g = np.linspace(0., 10.,num=5,retstep=True)
print(g)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)


In [ ]:
print(a[0:5])

[1. 2. 3. 4.]


In [ ]:
a = np.array([1,2,3,4,5,6],ndmin=2)
print(a.shape)
# print(a[,3:6])  # slicing range start:end and column position

(1, 6)


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
b = a[1:3,2:4]
print(b)

[[ 7  8]
 [11 12]]


In [ ]:
y = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(y)
row_r1 = y[1, :]
row_r2 = y[1:2,:]
row_r3 = y[[1],:]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b = np.array([0,2,0,1])
print(a[np.arange(4),b])
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))
print(np.argsort(a)[::-1])
print(np.where(a>5)[0])
print(np.where(a >= a[np.where(a)][0]))

In [ ]:
#delete(method) element in numpy
q = np.delete(a , [2,4])
print(q)

[ 1  2  4  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
k = np.array([[3,2,1],[6,5,4],[9,8,7]])
print(k)

y = np.sort(k , axis=1,kind = "quicksort")
print(y)


[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(v.dot(w))
print(np.dot(v,w))
print(v @ w)

219
219
219


In [ ]:
x = np.array([[1,2],[3,4],[5,6]])
print(x)
print(x.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [ ]:
print(x.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
z = w.squeeze() #concadenate
print(z)
z.shape

[11 12]


(2,)

In [ ]:
np.array([1,2,3])*5
np.array([[4,5,6],[7,8,9]])+np.array([1,2,3])

array([[ 5,  7,  9],
       [ 8, 10, 12]])

In [ ]:
np.array([[1],[2],[3]])+np.array([[4,5],[6,7],[8,9]])

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])